import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import BaseNavbar from '@/ui/Application/Navbars/BasicNavbar';
import { SessionProvider } from 'next-auth/react';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navbatTitle = 'Next';
  return (
    <html lang="zh-CN">
      <body className={`${inter.className}`}>
        <Providers>
          <main className="min-h-screen min-w-screen">
            <BaseNavbar title={navbatTitle} />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
